language: c
os: linux
dist: focal
compiler: gcc
git:
    submodules: false

before_install:
  - sudo apt update
  - sudo apt install -y clang-11 nasm

#before_script:
#  - sudo apt install -y build-essential uuid-dev iasl python3-distutils
#  - make init_submodules

script: make ci_knl

after_script: make clean_ci_knl
